name: "Delete PR review comments"
description: "Delete PR review comments by any conditions"
author: "aki77"
branding:
  icon: trash-2
  color: red
inputs:
  token:
    required: false
    description: "Github token"
    default: "${{ github.token }}"
  bodyContains:
    required: false
    description: "Delete only comments containing strings."
  noReply:
    required: false
    description: "Delete only comments with no replies."
    default: "false"
  pullRequestNumber:
    required: false
    description: "Delete comments on specified PR"
  usernames:
    required: false
    description: "Delete only comments posted by specified usernames (newline separated)"
  includeIssueComments:
    required: false
    description: "Include PR issue comments in deletion targets"
    default: "false"
  includeOverallReviewComments:
    required: false
    description: "Include overall review comments in deletion targets (will be hidden)"
    default: "false"
runs:
  using: "node20"
  main: "dist/index.js"
