name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: jdx/mise-action@c2a87611a18de5b3828c5652fe268e992400cb5c # v4.3.0
      - run: |
          npm install
      - run: |
          npm run all
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          usernames: |-
            aki77
          noReply: 'true'
          bodyContains: 'test2'
          includeIssueComments: 'true'
          includeOverallReviewComments: 'true'
